version: "3.9"

services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.0
    command: >
      start-dev
      --import-realm
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: password
      KC_DB: dev-mem
      KC_HTTP_RELATIVE_PATH: /
    volumes:
      - ./.compose/realm.json:/opt/keycloak/data/import/realm.json:Z
    ports:
      - "8001:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/realms/master"]
      interval: 10s
      timeout: 5s
      retries: 12
