name: Update built files
on:
  push:
    branches: [ 'master' ]
    paths-ignore:
      - '.sastscan.baseline'
      - 'pnpm-lock.yaml'
jobs:
  common:
    name: Build files
    runs-on: ubuntu-latest
    steps:

      - name: Check out repository
        uses: actions/checkout@v6
        with:
          token: ${{ secrets.PAT }}

      - name: Setup
        uses: ./.github/actions/setup
        with:
          node: 24

      - name: Update built files
        uses: ./.github/actions/update-built-files
        with:
          baseline-branch: 'master'
